### ISSUE TITLE
can't load the dataset

### ISSUE THREAD

**Issue by renatz** [KwanWaiChung/MT-Eval#2]
```
from datasets import load_dataset

tasks = [
  "refinement_single",
  "refinement_multi",
  "expansion_single",
  "expansion_multi",
  "follow-up_single",
  "follow-up_multi",
  "recollection_single_cls",
  "recollection_multiple_cls",
  "recollection_single_global-inst",
  "recollection_multi_global-inst",
]

data = load_dataset("wckwan/MT-Eval", tasks, split="test").to_list()
```

and got the error below:

```
Downloading data files: 100%|█████████████████████████████████████| 1/1 [00:00<00:00, 200.08it/s]

Extracting data files: 100%|███████████████████████████████████████| 1/1 [00:00<00:00, 84.66it/s]

Traceback (most recent call last):
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\builder.py", line 1875, in _prepare_split_single
    writer.write_table(table)
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\arrow_writer.py", line 568, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 2290, in table_cast
    return cast_table_to_schema(table, schema)
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 2249, in cast_table_to_schema
    arrays = [cast_array_to_feature(table[name], feature) for name, feature in features.items()]  
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 2249, in <listcomp>
    arrays = [cast_array_to_feature(table[name], feature) for name, feature in features.items()]  
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 1817, in wrapper   
    return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 1817, in <listcomp>
    return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 2048, in cast_array_to_feature
    casted_values = _c(array.values, feature[0])
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 1819, in wrapper   
    return func(array, *args, **kwargs)
  File "D:\coding\Anaconda3-2021.11\lib\site-packages\datasets\table.py", line 2110, in cast_array_to_feature
    raise TypeError(f"Couldn't cast array of type\n{array.type}\nto\n{feature}")
TypeError: Couldn't cast array of type
struct<user: string, sys: string, id: string, do_inference: bool>
to
{'user': Value(dtype='string', id=None), 'sys': Value(dtype='string', id=None), 'id': Value(dtype='string', id=None), 'do_inference': Value(dtype='bool', id=None), 'inst': Value(dtype='string', id=None)}
```

**Comment by KwanWaiChung** [comment]
The code to load the dataset should be
```python
from datasets import load_dataset

tasks = [
  "refinement_single",
  "refinement_multi",
  "expansion_single",
  "expansion_multi",
  "follow-up_single",
  "follow-up_multi",
  "recollection_single_cls",
  "recollection_multi_cls",
  "recollection_single_global-inst",
  "recollection_multi_global-inst",
]

for task in tasks:
    data = load_dataset('wckwan/MT-Eval', task, split='test')
```
I think you can download the dataset using this code. Please let me know if you have further questions.

**Comment by renatz** [comment]
@KwanWaiChung 
the code i pasted last day is in the 157 line of your inference.py module
and if I download with what you paste, the same error occurs below.
```
Downloading readme: 100%|██████████████████████████████████████████| 5.19k/5.19k [00:00<?, ?B/s]
Downloading and preparing dataset json/wckwan--MT-Eval to C:/Users/adwin/.cache/huggingface/datasets/wckwan___json/wckwan--MT-Eval-8294e17770bf7a6f/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data: 100%|█████████████████████████████████████| 73.2k/73.2k [00:00<00:00, 505kB/s]
Downloading data: 100%|██████████████████████████████████████| 208k/208k [00:00<00:00, 1.23MB/s]
Downloading data: 100%|██████████████████████████████████████| 584k/584k [00:00<00:00, 3.34MB/s]
Downloading data: 100%|██████████████████████████████████████| 452k/452k [00:00<00:00, 1.37MB/s]
Downloading data: 100%|███████████████████████████████████████| 144k/144k [00:00<00:00, 443kB/s]
Downloading data: 100%|███████████████████████████████████████| 230k/230k [00:00<00:00, 642kB/s]
Downloading data: 100%|███████████████████████████████████████| 174k/174k [00:00<00:00, 374kB/s]
Downloading data: 100%|███████████████████████████████████████| 114k/114k [00:00<00:00, 352kB/s]
Downloading data: 100%|██████████████████████████████████████| 393k/393k [00:00<00:00, 2.60MB/s]
Downloading data: 100%|███████████████████████████████████████| 550k/550k [00:00<00:00, 616kB/s]
Downloading data files: 100%|█████████████████████████████████████| 1/1 [00:17<00:00, 17.61s/it]
Extracting data files: 100%|█████████████████████████████████████| 1/1 [00:00<00:00, 100.00it/s] 
Traceback (most recent call last):
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\builder.py", line 1873, in _prepare_split_single
    writer.write_table(table)
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\arrow_writer.py", line 568, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 2290, in table_cast
    return cast_table_to_schema(table, schema)
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 2249, in cast_table_to_schema
    arrays = [cast_array_to_feature(table[name], feature) for name, feature in features.items()] 
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 2249, in <listcomp>
    arrays = [cast_array_to_feature(table[name], feature) for name, feature in features.items()] 
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 1817, in wrapper
    return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 1817, in <listcomp>
    return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 2048, in cast_array_to_feature
    casted_values = _c(array.values, feature[0])
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 1819, in wrapper
    return func(array, *args, **kwargs)
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\table.py", line 2110, in cast_array_to_feature
    raise TypeError(f"Couldn't cast array of type\n{array.type}\nto\n{feature}")
TypeError: Couldn't cast array of type
struct<user: string, sys: string, id: string, do_inference: bool>
to
{'user': Value(dtype='string', id=None), 'sys': Value(dtype='string', id=None), 'id': Value(dtype='string', id=None), 'do_inference': Value(dtype='bool', id=None), 'inst': Value(dtype='string', id=None)}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\runpy.py", line 87, in _run_code     
    exec(code, run_globals)
  File "E:\sci\ra\2-simu\code\workspace\down_ds\down.py", line 17, in <module>
    data = load_dataset('wckwan/MT-Eval', task, split='test')
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\load.py", line 1797, in load_dataset
    builder_instance.download_and_prepare(
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\builder.py", line 890, in download_and_prepare
    self._download_and_prepare(
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\builder.py", line 985, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\builder.py", line 1746, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "D:\coding\Anaconda3-2021.11\envs\inquirygpt-cli\lib\site-packages\datasets\builder.py", line 1891, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e        
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```

**Comment by renatz** [comment]
i revise the code and the script runs well
